# extras/kitty/oasis_mirage_dark.conf
## name: Oasis Mirage Dark
## author: uhs-robert

# Palette
color0                   #152229
color8                   #587270

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #68C0B6
color14                  #8FD1C7

color7                   #FFF7D7
color15                  #F7F4E9

# Core
foreground               #DDEFEF
background               #152229

# Selection
selection_background     #666666
selection_foreground     #DDEFEF

# Cursor
cursor                   #F0E68C
cursor_text_color        #152229

# Borders (panes)
active_border_color      #68C0B6
inactive_border_color    #1C2B31

# Tabs
active_tab_foreground    #152229
active_tab_background    #79C7BE
inactive_tab_foreground  #79C7BE
inactive_tab_background  #1C2B31
