# extras/kitty/oasis_sol_dark.conf
## name: Oasis Sol Dark
## author: uhs-robert

# Palette
color0                   #2A1412
color8                   #83615B

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #68C0B6
color14                  #8FD1C7

color7                   #FFF7D7
color15                  #F7F4E9

# Core
foreground               #FFE0DA
background               #2A1412

# Selection
selection_background     #666666
selection_foreground     #FFE0DA

# Cursor
cursor                   #F0E68C
cursor_text_color        #2A1412

# Borders (panes)
active_border_color      #FF7979
inactive_border_color    #341F1B

# Tabs
active_tab_foreground    #2A1412
active_tab_background    #FF7979
inactive_tab_foreground  #FF7979
inactive_tab_background  #341F1B
