# extras/kitty/oasis_night_dark.conf
## name: Oasis Night Dark
## author: uhs-robert

# Palette
color0                   #050F23
color8                   #536B83

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #68C0B6
color14                  #8FD1C7

color7                   #FFF7D7
color15                  #F7F4E9

# Core
foreground               #E8F1FF
background               #050F23

# Selection
selection_background     #666666
selection_foreground     #E8F1FF

# Cursor
cursor                   #F0E68C
cursor_text_color        #050F23

# Borders (panes)
active_border_color      #7FA3C9
inactive_border_color    #0B1832

# Tabs
active_tab_foreground    #050F23
active_tab_background    #7FA3C9
inactive_tab_foreground  #7FA3C9
inactive_tab_background  #0B1832
