# extras/kitty/oasis_rose_dark.conf
## name: Oasis Rose Dark
## author: uhs-robert

# Palette
color0                   #301828
color8                   #816175

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #68C0B6
color14                  #8FD1C7

color7                   #FFF7D7
color15                  #F7F4E9

# Core
foreground               #FADBE4
background               #301828

# Selection
selection_background     #666666
selection_foreground     #FADBE4

# Cursor
cursor                   #F0E68C
cursor_text_color        #301828

# Borders (panes)
active_border_color      #D18BA2
inactive_border_color    #3E2636

# Tabs
active_tab_foreground    #301828
active_tab_background    #DB9AB0
inactive_tab_foreground  #DB9AB0
inactive_tab_background  #3E2636
