# extras/kitty/oasis_scorpion_dark.conf
## name: Oasis Scorpion Dark
## author: uhs-robert

# Palette
color0                   #140400
color8                   #9A6F66

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #68C0B6
color14                  #8FD1C7

color7                   #FFF7D7
color15                  #F7F4E9

# Core
foreground               #F7EAE5
background               #140400

# Selection
selection_background     #666666
selection_foreground     #F7EAE5

# Cursor
cursor                   #F0E68C
cursor_text_color        #140400

# Borders (panes)
active_border_color      #C96E4D
inactive_border_color    #22100B

# Tabs
active_tab_foreground    #140400
active_tab_background    #F0E68C
inactive_tab_foreground  #F0E68C
inactive_tab_background  #22100B
