# extras/kitty/oasis_dune_dark.conf
## name: Oasis Dune Dark
## author: uhs-robert

# Palette
color0                   #29211C
color8                   #826D5A

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #68C0B6
color14                  #8FD1C7

color7                   #FFF7D7
color15                  #F7F4E9

# Core
foreground               #E8E5DA
background               #29211C

# Selection
selection_background     #666666
selection_foreground     #E8E5DA

# Cursor
cursor                   #F0E68C
cursor_text_color        #29211C

# Borders (panes)
active_border_color      #BDB76B
inactive_border_color    #352C26

# Tabs
active_tab_foreground    #29211C
active_tab_background    #D6CE7C
inactive_tab_foreground  #D6CE7C
inactive_tab_background  #352C26
