# extras/kitty/oasis_midnight_dark.conf
## name: Oasis Midnight Dark
## author: uhs-robert

# Palette
color0                   #101418
color8                   #4E6578

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #68C0B6
color14                  #8FD1C7

color7                   #FFF7D7
color15                  #F7F4E9

# Core
foreground               #F7F4F2
background               #101418

# Selection
selection_background     #666666
selection_foreground     #F7F4F2

# Cursor
cursor                   #F0E68C
cursor_text_color        #101418

# Borders (panes)
active_border_color      #FF7979
inactive_border_color    #18202A

# Tabs
active_tab_foreground    #101418
active_tab_background    #D6CE7C
inactive_tab_foreground  #D6CE7C
inactive_tab_background  #18202A
