# extras/kitty/oasis_lagoon_dark.conf
## name: Oasis Lagoon Dark
## author: uhs-robert

# Palette
color0                   #101825
color8                   #3B6A87

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #68C0B6
color14                  #8FD1C7

color7                   #FFF7D7
color15                  #F7F4E9

# Core
foreground               #D9E6FA
background               #101825

# Selection
selection_background     #666666
selection_foreground     #D9E6FA

# Cursor
cursor                   #F0E68C
cursor_text_color        #101825

# Borders (panes)
active_border_color      #3AACFD
inactive_border_color    #1A283F

# Tabs
active_tab_foreground    #101825
active_tab_background    #58B8FD
inactive_tab_foreground  #58B8FD
inactive_tab_background  #1A283F
