# extras/kitty/oasis_canyon_dark.conf
## name: Oasis Canyon Dark
## author: uhs-robert

# Palette
color0                   #2B1914
color8                   #9A6549

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #68C0B6
color14                  #8FD1C7

color7                   #FFF7D7
color15                  #F7F4E9

# Core
foreground               #F8E7D3
background               #2B1914

# Selection
selection_background     #666666
selection_foreground     #F8E7D3

# Cursor
cursor                   #F0E68C
cursor_text_color        #2B1914

# Borders (panes)
active_border_color      #FFA34D
inactive_border_color    #38251E

# Tabs
active_tab_foreground    #2B1914
active_tab_background    #FFBA75
inactive_tab_foreground  #FFBA75
inactive_tab_background  #38251E
