# extras/kitty/oasis_cactus_dark.conf
## name: Oasis Cactus Dark
## author: uhs-robert

# Palette
color0                   #18231A
color8                   #5B7360

color1                   #FF7979
color9                   #FFA0A0

color2                   #7FCF78
color10                  #A3E39A

color3                   #F0E68C
color11                  #F8B471

color4                   #81C0FF
color12                  #87CEEB

color5                   #C695FF
color13                  #D2ADFF

color6                   #68C0B6
color14                  #8FD1C7

color7                   #FFF7D7
color15                  #F7F4E9

# Core
foreground               #DDF0E5
background               #18231A

# Selection
selection_background     #666666
selection_foreground     #DDF0E5

# Cursor
cursor                   #F0E68C
cursor_text_color        #18231A

# Borders (panes)
active_border_color      #7FBB82
inactive_border_color    #253127

# Tabs
active_tab_foreground    #18231A
active_tab_background    #7FBB82
inactive_tab_foreground  #7FBB82
inactive_tab_background  #253127
