git clone git://repo.or.cz/vcscommand 
git clone https://github.com/Lokaltog/vim-powerline.git
git clone https://github.com/kien/ctrlp.vim.git
git clone https://github.com/msanders/snipmate.vim
git clone https://github.com/scrooloose/nerdtree.git
git clone https://github.com/scrooloose/syntastic.git
git clone https://github.com/sjl/clam.vim.git
git clone https://github.com/sjl/gundo.vim.git
git clone https://github.com/sjl/splice.vim
git clone https://github.com/tpope/vim-abolish.git 
git clone https://github.com/tpope/vim-pathogen.git
git clone https://github.com/vim-scripts/VimClojure.git
