
return { 
	{
		"zaldih/themery.nvim",
		lazy = false,
		config = function()
			require("themery").setup({
				-- add the config here
			      themes = {
					-- "Tier 1"
					"paragon",
					"rakis",
					"silkcircuit",
					"sora",
					"jb",
					"chai",
					"everforest",
					"bamboo",
					"bamboo-light",
					"bamboo-multiplex",
					"bamboo-vulgaris",
					"farout",
					"farout-day",
					"farout-moon",
					"farout-night",
					"farout-storm",
					"kanagawa",
					"kanagawa-dragon",
					"kanagawa-lotus",
					"kanagawa-wave",
					"oasis",
					"oasis-abyss",
					"oasis-cactus",
					"oasis-canyon",
					"oasis-desert",
					"oasis-dune",
					"oasis-lagoon",
					"oasis-luna",
					"oasis-midnight",
					"oasis-mirage",
					"oasis-moonlight",
					"oasis-night",
					"oasis-rose",
					"oasis-scorpion",
					"oasis-sol",
					"oasis-starlight",
					"oasis-twilight",
					-- "Tier 2"
					"andromeda",
					"bathory",
					"bathory-alt",
					"bebop",
					"black-metal-day",
					"black-metal-day-alt",
					"burzum",
					"burzum-alt",
					"candyland",
					"citruszest",
					"dark-funeral",
					"dark-funeral-alt",
					"darkthrone",
					"darkthrone-alt",
					"ember",
					"ember-auto",
					"ember-light",
					"ember-soft",
					"emperor",
					"emperor-alt",
					"evangelion",
					"everblush",
					"evergarden",
					"evergarden-fall",
					"evergarden-spring",
					"evergarden-summer",
					"evergarden-winter",
					"gorgoroth",
					"gorgoroth-alt",
					"gruvbox-baby",
					"gruvbox-minor",
					"heatherfield",
					"hybrid",
					"immortal",
					"immortal-alt",
					"impaled-nazarene",
					"impaled-nazarene-alt",
					"khold",
					"khold-alt",
					"koda",
					"koda-dark",
					"koda-glade",
					"koda-light",
					"koda-moss",
					"marduk",
					"marduk-alt",
					"mayhem",
					"mayhem-alt",
					"melange",
					"mellifluous",
					"midnight",
					"nightblossom",
					"nightblossom-pastel",
					"nightblossom-sakura",
					"nightly",
					"nightsky",
					"nile",
					"nile-alt",
					"oldtale",
					"posterpole",
					"pustota",
					"radium",
					"slack",
					"slatewave",
					"taake",
					"taake-alt",
					"terracotta",
					"thematrix",
					"thorn",
					"thorn-dark-cold",
					"thorn-dark-warm",
					"thorn-light-cold",
					"thorn-light-warm",
					"thyrfing",
					"thyrfing-alt",
					"tzfn",
					"tzfn-light",
					"tzfn-main",
					"vague",
					"venom",
					"venom-alt",
					"vesper",
					"vhs-era-theme",
					"voblue",
					"windir",
					"windir-alt",
					"witchesbrew",
					"witchesbrew-bright",
					"yash",
					-- "Tier 3"
					--"angelic",
					--"antares",
					--"fleet",
					--"habamax.nvim",
					--"harlequin",
					--"nightwolf",
					--"nightwolf-black",
					--"nightwolf-dark-blue",
					--"nightwolf-dark-gray",
					--"nightwolf-gray",
					--"nightwolf-light",
					--"nisha",
					--"noctis",
					--"nortia-nvim",
					--"oxide",
					--"sakura",
					--"starrynight",
					--"tender",
					--"truedark",
					--"vorange",
				}, -- Your list of installed colorschemes.
			      livePreview = true, -- Apply theme while picking. Default to true.
			})
		end
	},
	{
		"caenrique/nvim-maximize-window-toggle",
		config = function()
			vim.keymap.set("n", "<S-CR>", ":ToggleOnly<CR>")
		end,
	},
	-- highlight RGB colors in files
	{ "brenoprata10/nvim-highlight-colors", opts = {} },
	{
		"max397574/colortils.nvim",
		opts = {},
		config = function()
			require("colortils").setup({})
		end,
	},
	{
		'kevinlangleyjr/neovim-slatewave',
		name = 'slatewave',
		priority = 1000,
		lazy = false,
		opts = {},
		config = function(_, opts)
			require('slatewave').setup(opts)
			vim.cmd.colorscheme('slatewave')
		end,
	},
	{ "jacoborus/tender.vim" },
	{ "rebelot/kanagawa.nvim" },
	{
		-- alow setting theme by file type
		"folke/styler.nvim",
		opts = {
			themes = {
				markdown = { colorscheme = "kanagawa-wave" },
			},
		},
	},
	{ "savq/melange-nvim" },
	{ "ribru17/bamboo.nvim" },
	{ "everviolet/nvim", 
		name = "everviolet" },
	{ "vague-theme/vague.nvim" },
	{ "luisiacc/gruvbox-baby" },
	{ "metalelf0/black-metal-theme-neovim" },
	{ "luisiacc/gruvbox-baby" },
	{ "ramojus/mellifluous.nvim" },
	{ "neanias/everforest-nvim" },
	{ "Everblush/nvim",
		name = "everblush"
	},
	{ "oskarnurm/koda.nvim" },
	{ "zootedb0t/citruszest.nvim" },
	{ "dasupradyumna/midnight.nvim" },
	{ "datsfilipe/vesper.nvim" },
	{ "ilof2/posterpole.nvim" },
	{ "xero/evangelion.nvim" },
	{ "HoNamDuong/hybrid.nvim" },
	{ "uhs-robert/oasis.nvim" },
	{ "nickkadutskyi/jb.nvim" },
	{ "kartikp10/noctis.nvim" },
	{ "rileytwo/kiss" },
	{ "ember-theme/nvim", 
		name = "ember" },
	{ "jpwol/thorn.nvim" },
	{ "felipeagc/fleet-theme-nvim" },
	{ "Alexis12119/nightly.nvim" },
	{ "anAcc22/sakura.nvim" },
	{ "hyperb1iss/silkcircuit" },
	{ "nielsmadan/harlequin" },
	{ "ricardoraposo/nightwolf.nvim" },
	{ "AmberLehmann/candyland.nvim" },
	{ "Aejkatappaja/sora" },
	{ "Malick-Tammal/monokai-neovim" },
	{ "luisiacc/the-matrix.nvim" },
	{ "ntk148v/habamax.nvim" },
	{ "ATTron/bebop.nvim" },
	{ "rijulpaul/nightblossom.nvim" },
	{ "kihachi2000/yash.nvim" },
	{ "heraldofsolace/nisha-vim" },
	{ "josegamez82/starrynight" },
	{ "Marfisc/vorange" },
	{ "nobbmaestro/nvim-andromeda" },
	{ "alaric/nortia.nvim" },
	{ "baliestri/aura-theme" },
	{ "sponkurtus2/angelic.nvim" },
	{ "bratpeki/truedark-vim" },
	{ "Haron-Prime/Antares" },
	{ "thallada/farout.nvim" },
	{ "mistweaverco/vhs-era-theme.nvim" },
	{ "oxidescheme/nvim",
		name = "oxide" },
	{ "ricardoraposo/gruvbox-minor.nvim" },
	{ "topazape/oldtale.nvim" },
	{ "Shobhit-Nagpal/chai.nvim" },
	{ "sirzif/tzfn.nvim" },
	{ "pustota-theme/pustota.nvim" },
	{ "shoenot/witchesbrew.nvim" },
	{ "egerhether/heatherfield.nvim" },
	{ "noorwachid/nvim-nightsky" },
	{ "Sly-Harvey/radium.nvim" },
	{ "Pearljak/terracotta.nvim" },
	{ "sample-usr/rakis.nvim" },
	{ "ntk148v/slack.nvim" },
	{ "AntonyZ89/electron-vue.nvim" },
	{ "nnavales/paragon" },
}
