#!/bin/bash

action=$1
shift

function usage(){
  echo "  Navigate to URL:"
  echo "    nav ITEM#"
  echo "      Searches for a URL in the todo line and launches a browser."
  echo ""
  exit
}

[ "$action" = "usage" ] && usage

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
    echo "Error! Usage:"
    usage
fi

URL=$(sed "$1!d" "$TODO_FILE"|grep -E -o "([a-z]*)://[^ ]+")
if [ "$URL" = "" ]; then
    LINE=$(sed "$1!d" "$TODO_FILE")
    if [ "$LINE" = "" ]; then
        echo "Error, no item #$1 found!"
    else
        echo "Error, no URL seen in item #$1!"
        echo "$LINE"
    fi
    exit 1
fi

open "$URL"
